// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides personalized fitness advice and guidance via AI consultation tool.
 *
 * - aiFitnessAdvice - A function that handles the AI fitness advice process.
 * - AiFitnessAdviceInput - The input type for the aiFitnessAdvice function.
 * - AiFitnessAdviceOutput - The return type for the aiFitnessAdvice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiFitnessAdviceInputSchema = z.object({
  workoutLogs: z
    .string()
    .describe('The workout logs of the user, including exercises, sets, reps, and weight.'),
  bodyComposition: z
    .string()
    .describe('The body composition analysis of the user, including BMI and muscle mass.'),
  fitnessGoals: z.string().describe('The fitness goals of the user.'),
  age: z.number().describe('The age of the user.'),
  gender: z.string().describe('The gender of the user.'),
});

export type AiFitnessAdviceInput = z.infer<typeof AiFitnessAdviceInputSchema>;

const AiFitnessAdviceOutputSchema = z.object({
  advice: z.string().describe('The personalized fitness advice and guidance.'),
});

export type AiFitnessAdviceOutput = z.infer<typeof AiFitnessAdviceOutputSchema>;

export async function aiFitnessAdvice(input: AiFitnessAdviceInput): Promise<AiFitnessAdviceOutput> {
  return aiFitnessAdviceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiFitnessAdvicePrompt',
  input: {schema: AiFitnessAdviceInputSchema},
  output: {schema: AiFitnessAdviceOutputSchema},
  prompt: `You are an AI fitness trainer. Provide personalized fitness advice and guidance based on the user's workout logs, body composition analysis, fitness goals, age and gender.

Workout Logs: {{{workoutLogs}}}
Body Composition: {{{bodyComposition}}}
Fitness Goals: {{{fitnessGoals}}}
Age: {{{age}}}
Gender: {{{gender}}}

Provide personalized fitness advice and guidance.`,
});

const aiFitnessAdviceFlow = ai.defineFlow(
  {
    name: 'aiFitnessAdviceFlow',
    inputSchema: AiFitnessAdviceInputSchema,
    outputSchema: AiFitnessAdviceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
